spring:
  security:
    user:
      name: teoan
      password: 277077411
eureka:
  client:
    instance: localhost
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 4000 # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒