spring:
  datasource: #数据库连接配置
    type: com.alibaba.druid.pool.DruidDataSource
    username: teoan
    password: 277077411
    url: jdbc:mysql://www.xumumi.com:3306/tclass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      stat-view-servlet:
        login-username: Teoan
        login-password: 277077411
  redis:
    host: www.xumumi.com
    database: 0
    port: 6379
    password: 277077411
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true #优先使用IP地址注册
  client:
    service-url:
      defaultZone: http://teoan:277077411@localhost:8761/eureka/ #eureka的注册地址
mybatis-plus:
  global-config:
    banner: false

oauth2:
  resource:
    permit-all-paths: /oauth/login,/oauth/verifyCode.jpg #配置认证放行路径