server:
  port: 9999 #服务端口
spring:
  profiles:
    active: dev #环境
  datasource: #数据库连接配置
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 277077411
    url: jdbc:mysql://localhost:3306/tclass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      stat-view-servlet:
        login-username: Teoan
        login-password: 277077411
  redis:
    host: www.xumumi.com
    database: 0
    port: 6379
    password: 13319711
  main:
    allow-bean-definition-overriding: true
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true #优先使用IP地址注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka的注册地址