server:
  servlet:
    context-path: "/notice"
spring:
  datasource: #数据库连接配置
    type: com.alibaba.druid.pool.DruidDataSource
    username: teoan
    password: 277077411
    url: jdbc:mysql://mysql:3306/tclass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      stat-view-servlet:
        login-username: Teoan
        login-password: 277077411
  redis:
    host: redis
    database: 0
    port: 6379
    password: 277077411
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #配置文件上传大小
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 50MB
  #将前端传来的String解析为Data
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true #优先使用IP地址注册
  client:
    service-url:
      defaultZone: http://tclass-registry:8761/eureka/ #eureka的注册地址
mybatis-plus:
  global-config:
    banner: false